-- Release 4 Slice 6: Shopping toilet paper POC and evidence-to-score readiness.
-- Real product/source records only. External scorecards are evidence references,
-- not Mishava Scores. Public score fields stay null until Mishava-reviewed
-- claims and a supported scoring version exist.

alter table public.shopping_products
  add column if not exists recycled_content_claim text,
  add column if not exists post_consumer_recycled_content_claim text,
  add column if not exists bamboo_fsc_claim text,
  add column if not exists virgin_fiber_claim text,
  add column if not exists bleaching_process_claim text,
  add column if not exists packaging_claim text,
  add column if not exists brand_sourcing_policy_url text,
  add column if not exists external_evidence_reference_url text,
  add column if not exists external_evidence_reference_notes text,
  add column if not exists mishava_evidence_review_status text not null default 'not_started';

alter table public.shopping_products
  drop constraint if exists shopping_products_baby_poc_subcategory_check,
  add constraint shopping_products_baby_poc_subcategory_check
    check (
      product_subcategory is null
      or product_subcategory in ('diapers', 'wipes', 'toilet-paper')
    );

alter table public.shopping_products
  drop constraint if exists shopping_products_evidence_review_status_check;

alter table public.shopping_products
  add constraint shopping_products_evidence_review_status_check
    check (
      mishava_evidence_review_status in (
        'not_started',
        'external_evidence_available',
        'draft_claims',
        'reviewed_claims',
        'score_ready'
      )
    );

alter table public.shopping_products
  drop constraint if exists shopping_products_toilet_paper_score_requires_mishava_review;

alter table public.shopping_products
  add constraint shopping_products_toilet_paper_score_requires_mishava_review
    check (
      mishava_evidence_review_status = 'score_ready'
      or (
        evidence_score is null
        and score_label is null
        and score_snapshot_id is null
        and score_published_at is null
      )
    );

insert into public.shopping_products (
  id,
  slug,
  name,
  brand_name,
  category,
  product_subcategory,
  product_summary,
  package_details,
  product_url,
  image_url,
  image_alt_text,
  image_source_url,
  image_source_type,
  image_review_status,
  image_last_reviewed_at,
  image_rights_notes,
  evidence_score,
  score_label,
  evidence_coverage,
  evidence_recency,
  verification_confidence,
  score_snapshot_id,
  score_published_at,
  source_name,
  source_url,
  source_captured_at,
  source_review_status,
  data_origin,
  recycled_content_claim,
  post_consumer_recycled_content_claim,
  bamboo_fsc_claim,
  virgin_fiber_claim,
  bleaching_process_claim,
  packaging_claim,
  brand_sourcing_policy_url,
  external_evidence_reference_url,
  external_evidence_reference_notes,
  mishava_evidence_review_status,
  active
)
values
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f001',
    'charmin-ultra-soft-toilet-paper-18-mega-rolls',
    'Charmin Ultra Soft Toilet Paper - 18 Mega Rolls',
    'Charmin',
    'household',
    'toilet-paper',
    'Mainstream toilet paper product recorded for the toilet paper POC. Mishava has source metadata and external evidence references, but no reviewed scoring claims yet.',
    '18 mega rolls',
    'https://www.target.com/p/-/A-78603885',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-78603885',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    null,
    'Virgin fiber reliance not reviewed by Mishava.',
    null,
    null,
    'https://www.charmin.com/en-us',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f002',
    'cottonelle-ultra-clean-toilet-paper-24-mega-rolls',
    'Cottonelle Ultra Clean Toilet Paper - 24 Mega Rolls',
    'Cottonelle',
    'household',
    'toilet-paper',
    'Mainstream toilet paper product recorded for the toilet paper POC. Mishava has source metadata and external evidence references, but no reviewed scoring claims yet.',
    '24 mega rolls',
    'https://www.target.com/p/-/A-79762902',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-79762902',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    null,
    'Virgin fiber reliance not reviewed by Mishava.',
    null,
    null,
    'https://www.cottonelle.com/en-us',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f003',
    'angel-soft-toilet-paper-18-mega-rolls',
    'Angel Soft Toilet Paper - 18 Mega Rolls',
    'Angel Soft',
    'household',
    'toilet-paper',
    'Mainstream toilet paper product recorded for the toilet paper POC. Mishava has source metadata and external evidence references, but no reviewed scoring claims yet.',
    '18 mega rolls',
    'https://www.target.com/p/-/A-92581983',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-92581983',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    null,
    'Virgin fiber reliance not reviewed by Mishava.',
    null,
    null,
    'https://www.angelsoft.com/products/angel-soft-toilet-paper',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f004',
    'quilted-northern-ultra-plush-toilet-paper-18-mega-rolls',
    'Quilted Northern Ultra Plush Toilet Paper - 18 Mega Rolls',
    'Quilted Northern',
    'household',
    'toilet-paper',
    'Mainstream toilet paper product recorded for the toilet paper POC. Mishava has source metadata and external evidence references, but no reviewed scoring claims yet.',
    '18 mega rolls',
    'https://www.target.com/p/-/A-81566325',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-81566325',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    null,
    'Virgin fiber reliance not reviewed by Mishava.',
    null,
    null,
    'https://www.quiltednorthern.com/',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f005',
    'scott-1000-toilet-paper-20-rolls',
    'Scott 1000 Toilet Paper - 20 Rolls',
    'Scott',
    'household',
    'toilet-paper',
    'Mainstream septic-safe toilet paper product recorded for the toilet paper POC. Mishava has source metadata and external evidence references, but no reviewed scoring claims yet.',
    '20 rolls',
    'https://www.target.com/p/-/A-83459186',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-83459186',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    null,
    'Virgin fiber reliance not reviewed by Mishava.',
    null,
    null,
    'https://www.scottbrand.com/en-us/products/toilet-paper',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f006',
    'up-and-up-soft-strong-toilet-paper-30-mega-rolls',
    'Soft & Strong Toilet Paper - 30 Mega Rolls - up&up',
    'up&up',
    'household',
    'toilet-paper',
    'Target-owned private-label toilet paper product recorded for the toilet paper POC. Mishava has source metadata and external evidence references, but no reviewed scoring claims yet.',
    '30 mega rolls',
    'https://www.target.com/p/-/A-91258643',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-91258643',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    null,
    'Virgin fiber reliance not reviewed by Mishava.',
    null,
    null,
    'https://www.target.com/c/up-up/-/N-q643lecy87s',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f007',
    'seventh-generation-100-recycled-toilet-paper-24-rolls',
    'Seventh Generation 100% Recycled Toilet Paper - 24 Rolls',
    'Seventh Generation',
    'household',
    'toilet-paper',
    'Recycled toilet paper product recorded for the toilet paper POC. Recycled-content claims are captured as draft evidence metadata, not a Mishava Score.',
    '24 rolls',
    'https://www.target.com/p/-/A-80959297',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-80959297',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    'Product name/source describes 100% recycled toilet paper.',
    'Post-consumer recycled percentage not yet reviewed by Mishava.',
    null,
    'Virgin fiber reliance requires Mishava review.',
    'Bleaching/process claims not yet reviewed by Mishava.',
    'Packaging claims not yet reviewed by Mishava.',
    'https://www.seventhgeneration.com/',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f008',
    'reel-premium-bamboo-toilet-paper-24-rolls',
    'Reel Premium Bamboo Toilet Paper - 24 Rolls',
    'Reel',
    'household',
    'toilet-paper',
    'Bamboo toilet paper product recorded for the toilet paper POC. Bamboo/FSC-related claims are captured as draft evidence metadata, not a Mishava Score.',
    '24 rolls',
    'https://www.target.com/p/-/A-94731844',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target product page',
    'https://www.target.com/p/-/A-94731844',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    'Bamboo claim recorded from product/source metadata; certification status requires Mishava review.',
    'Virgin fiber reliance requires Mishava review.',
    'Bleaching/process claims not yet reviewed by Mishava.',
    'Packaging claims not yet reviewed by Mishava.',
    'https://reelpaper.com/products/premium-bamboo-toilet-paper',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  ),
  (
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f009',
    'caboo-tree-free-bamboo-toilet-paper-24-rolls',
    'Caboo Tree Free Bamboo Toilet Paper - 24 Rolls',
    'Caboo',
    'household',
    'toilet-paper',
    'Tree-free bamboo toilet paper product recorded for the toilet paper POC. Bamboo-related claims are captured as draft evidence metadata, not a Mishava Score.',
    '24 rolls',
    'https://www.target.com/s?searchTerm=Caboo%20bamboo%20toilet%20paper',
    null,
    null,
    null,
    null,
    'missing',
    null,
    'No product image is displayed until image rights are reviewed and approved.',
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'Target search/product listing page',
    'https://www.target.com/s?searchTerm=Caboo%20bamboo%20toilet%20paper',
    '2026-05-26T00:00:00Z',
    'approved',
    'retailer_page',
    null,
    null,
    'Bamboo/tree-free claim recorded from product/source metadata; certification status requires Mishava review.',
    'Virgin fiber reliance requires Mishava review.',
    'Bleaching/process claims not yet reviewed by Mishava.',
    'Packaging claims not yet reviewed by Mishava.',
    'https://cabooproducts.com/',
    'https://www.nrdc.org/resources/issue-tissue-how-americans-are-flushing-forests-down-toilet',
    'External tissue sustainability scorecards may be used as evidence references only; no external score is copied as a Mishava Score.',
    'external_evidence_available',
    true
  )
on conflict (slug) do update
set
  name = excluded.name,
  brand_name = excluded.brand_name,
  category = excluded.category,
  product_subcategory = excluded.product_subcategory,
  product_summary = excluded.product_summary,
  package_details = excluded.package_details,
  product_url = excluded.product_url,
  image_url = null,
  image_alt_text = null,
  image_source_url = null,
  image_source_type = null,
  image_review_status = 'missing',
  image_last_reviewed_at = null,
  image_rights_notes = excluded.image_rights_notes,
  evidence_score = null,
  score_label = null,
  evidence_coverage = null,
  evidence_recency = null,
  verification_confidence = null,
  score_snapshot_id = null,
  score_published_at = null,
  source_name = excluded.source_name,
  source_url = excluded.source_url,
  source_captured_at = excluded.source_captured_at,
  source_review_status = excluded.source_review_status,
  data_origin = excluded.data_origin,
  recycled_content_claim = excluded.recycled_content_claim,
  post_consumer_recycled_content_claim = excluded.post_consumer_recycled_content_claim,
  bamboo_fsc_claim = excluded.bamboo_fsc_claim,
  virgin_fiber_claim = excluded.virgin_fiber_claim,
  bleaching_process_claim = excluded.bleaching_process_claim,
  packaging_claim = excluded.packaging_claim,
  brand_sourcing_policy_url = excluded.brand_sourcing_policy_url,
  external_evidence_reference_url = excluded.external_evidence_reference_url,
  external_evidence_reference_notes = excluded.external_evidence_reference_notes,
  mishava_evidence_review_status = excluded.mishava_evidence_review_status,
  active = excluded.active,
  updated_at = now();

insert into public.shopping_places_to_buy (
  id,
  product_id,
  seller_name,
  seller_type,
  url,
  price_cents,
  currency,
  availability_status,
  fulfillment_notes,
  local_pickup,
  local_delivery,
  active,
  last_checked_at,
  source_url,
  source_captured_at,
  source_review_status
)
values
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f001',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f001',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-78603885',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-78603885',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f002',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f002',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-79762902',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-79762902',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f003',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f003',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-92581983',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-92581983',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f004',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f004',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-81566325',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-81566325',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f005',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f005',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-83459186',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-83459186',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f006',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f006',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-91258643',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-91258643',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f007',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f007',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-80959297',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-80959297',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f008',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f008',
    'Target',
    'external_retailer',
    'https://www.target.com/p/-/A-94731844',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/p/-/A-94731844',
    '2026-05-26T00:00:00Z',
    'approved'
  ),
  (
    'ccbd7b6f-ec45-41a4-b94b-1c8896e6f009',
    '6c2f3b20-9e3a-4a81-8c6e-4ef8f3b9f009',
    'Target',
    'external_retailer',
    'https://www.target.com/s?searchTerm=Caboo%20bamboo%20toilet%20paper',
    null,
    'USD',
    'Availability not reviewed',
    'External seller page only; Mishava does not provide checkout.',
    false,
    false,
    true,
    '2026-05-26T00:00:00Z',
    'https://www.target.com/s?searchTerm=Caboo%20bamboo%20toilet%20paper',
    '2026-05-26T00:00:00Z',
    'approved'
  )
on conflict (id) do update
set
  seller_name = excluded.seller_name,
  seller_type = excluded.seller_type,
  url = excluded.url,
  price_cents = excluded.price_cents,
  currency = excluded.currency,
  availability_status = excluded.availability_status,
  fulfillment_notes = excluded.fulfillment_notes,
  local_pickup = excluded.local_pickup,
  local_delivery = excluded.local_delivery,
  active = excluded.active,
  last_checked_at = excluded.last_checked_at,
  source_url = excluded.source_url,
  source_captured_at = excluded.source_captured_at,
  source_review_status = excluded.source_review_status,
  updated_at = now();
